name: daily_buddy_app
description: A mental health assistant for daily structure.

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^0.4.0
  path_provider: ^1.6.5
  equatable: ^1.1.1
  jiffy: ^3.0.1
  nanoid: ^0.1.0
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  flutter_form_bloc: ^0.12.2
  flutter_local_notifications: ^1.4.0
  flutter_week_view: ^0.2.1
  day_night_switcher: ^0.1.0
  flutter_colorpicker: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: "^0.7.4"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Logo_Projekt_01.png
    - assets/Logo_Projekt_02.png

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/logo_no_border.png"
